/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

/**
 *
 * @author enriq
 */
public class ElementoListaMensajes extends javax.swing.JPanel {
    private String enunciado = "Enunciado";
    private int numeroOpciones = 3;
    /**
     * Creates new form panelPregunta
     */
    public ElementoListaMensajes() {
        initComponents();
    }

    public String getEnunciado(){
        return this.enunciado;
    }
    
    public int getNumeroOpciones(){
        return this.numeroOpciones;
    }
    
    public void setEnunciado(String enun){
        this.enunciado = enun;
        this.labelEnunciado.setText(enun);
    }
    
    public void setNumeroOpciones(int n){
        this.numeroOpciones = n;
        this.labelNumeroOpciones.setText(n + " opciones");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEnunciado = new javax.swing.JLabel();
        labelNumeroOpciones = new javax.swing.JLabel();

        labelEnunciado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelEnunciado.setText("Enunciado");

        labelNumeroOpciones.setText("Número de opciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEnunciado)
                    .addComponent(labelNumeroOpciones))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEnunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNumeroOpciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelEnunciado;
    private javax.swing.JLabel labelNumeroOpciones;
    // End of variables declaration//GEN-END:variables
}
