/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author enriq
 */
public class PanelAvatar extends javax.swing.JPanel {
    private ImageIcon icon;
    private Image rescaledIcon;
    private static final int DIMENSION_AVATAR = 64;
    private static final ImageIcon DEFAULTICON = new ImageIcon(PanelAvatar.class.getResource("icon.png"));
    /**
     * Creates new form panelAvatar    /**
     * Creates new form panelAvatar    /**
     * Creates new form panelAvatar    /**
     * Creates new form panelAvatar
     */
    
    public PanelAvatar(){
        this(DEFAULTICON);
    }
    
    public PanelAvatar(ImageIcon icon) {
        this.setPreferredSize(new Dimension(DIMENSION_AVATAR, DIMENSION_AVATAR));
        this.icon = icon;
        this.rescaledIcon = icon.getImage().getScaledInstance(DIMENSION_AVATAR, DIMENSION_AVATAR, Image.SCALE_DEFAULT);
    }
  
    
    public ImageIcon getIcon(){
        return icon;
    }
    
    public Image getRescaledIcon(){
        return rescaledIcon;
    }
    
    public void setIcon(ImageIcon icon){
        if(icon != null){
            this.icon = icon;
            this.rescaledIcon = icon.getImage();//.getScaledInstance(DIMENSION_AVATAR, DIMENSION_AVATAR, Image.SCALE_DEFAULT);
        }else 
            this.rescaledIcon = DEFAULTICON.getImage();
        this.repaint();
    }
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(rescaledIcon, 0, 0, this.getWidth(), this.getHeight(), null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
