/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.controller.ModificarPerfilController;
import abd.p1.model.Genero;
import abd.p1.model.Usuario;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

public class PanelPerfil extends javax.swing.JPanel {

    private boolean editable;
    private ModificarPerfilController controller;
    private DefaultListModel<String> listModel;
    
    /**
    * Creates new form PanelPerfil
    */
    public PanelPerfil() {
        initComponents();
        inicializarListeners();
         //Lista de aficiones
        listModel = new DefaultListModel<String>();
        jListAficiones.setModel(listModel);
    }
    
    public void setEditable(boolean editable) {
        this.editable = editable;
        this.anadirAficion.setVisible(editable);
        this.cambiarAvatar.setVisible(editable);
        this.cambiarPreferencia.setVisible(editable);
        this.cambiarSexo.setVisible(editable);
        this.editarSeleccionada.setVisible(editable);
        this.eliminarSeleccionada.setVisible(editable);
        this.userPanel.setEditable(editable);
        this.areaDescripcion.setEditable(editable);
    }
    
    public boolean getEditable() {
        return this.editable;
    }
    
    public void setController(ModificarPerfilController controller) {
        this.controller = controller;
        userPanel.setController(controller);
    }
    
    public ModificarPerfilController getController() {
        return this.controller;
    }
    
    public String getDescripcion() {
        return areaDescripcion.getText();
    }
    
    public void rellenarDatos(Usuario user) {
        areaDescripcion.setText(user.getDescripcion());
        labelSexo.setText(user.getGenero().toString());
        labelGeneroInteres.setText(user.getGeneroInteres().toString());
        //Rellenamos las aficiones
        for (String aficion: user.getAficiones()) {
            listModel.addElement(aficion);
        }
        userPanel.rellenarInfo(user.getNombre(), user.getImagen(), user.getFechaNac());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cambiarPreferencia = new javax.swing.JButton();
        cambiarSexo = new javax.swing.JButton();
        editarSeleccionada = new javax.swing.JButton();
        eliminarSeleccionada = new javax.swing.JButton();
        anadirAficion = new javax.swing.JButton();
        cambiarAvatar = new javax.swing.JButton();
        labelDescripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaDescripcion = new javax.swing.JTextArea();
        labelAficiones = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        busca = new javax.swing.JLabel();
        labelSexo = new javax.swing.JLabel();
        labelGeneroInteres = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAficiones = new javax.swing.JList<>();
        userPanel = new abd.p1.view.UserPanel();

        cambiarPreferencia.setText("Cambiar preferencia");

        cambiarSexo.setText("Cambiar sexo");

        editarSeleccionada.setText("Editar seleccionada");

        eliminarSeleccionada.setText("Eliminar seleccionada");

        anadirAficion.setText("Añadir afición");

        cambiarAvatar.setText("Cambiar avatar");

        labelDescripcion.setText("Descripción:");

        areaDescripcion.setColumns(20);
        areaDescripcion.setRows(5);
        jScrollPane2.setViewportView(areaDescripcion);

        labelAficiones.setText("Aficiones:");

        sexo.setText("Sexo:");

        busca.setText("Busca:");

        jScrollPane1.setViewportView(jListAficiones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(busca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelGeneroInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(257, 257, 257)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cambiarPreferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cambiarSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelDescripcion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(labelAficiones))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cambiarAvatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(anadirAficion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editarSeleccionada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eliminarSeleccionada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiarAvatar))
                .addGap(16, 16, 16)
                .addComponent(labelAficiones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sexo)
                                .addComponent(cambiarSexo))
                            .addComponent(labelSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(cambiarPreferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(busca)
                            .addComponent(labelGeneroInteres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anadirAficion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editarSeleccionada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarSeleccionada)))
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void inicializarListeners() {
        cambiarAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarAvatarActionPerformed(evt);
            }
        });

        anadirAficion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirAficionActionPerformed(evt);
            }
        });
        
        editarSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarSeleccionadaActionPerformed(evt);
            }
        });
        
        eliminarSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarSeleccionadaActionPerformed(evt);
            }
        });
         
        cambiarSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarSexoActionPerformed(evt);
            }
        });
        
        cambiarPreferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarPreferenciaActionPerformed(evt);
            }
        });
        
    }
    
    private void cambiarAvatarActionPerformed(java.awt.event.ActionEvent evt) {
        ImageIcon avatar = controller.cambiarAvatar();
        if (avatar != null) {
            userPanel.setIcon(avatar);
        }
    }
    
    private void anadirAficionActionPerformed(java.awt.event.ActionEvent evt) {
        String aficion = controller.añadirAficion();
        if (aficion != null) {
           listModel.addElement(aficion);
        }
    }
     
    private void editarSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {
       String aficion = jListAficiones.getSelectedValue();
       if (aficion != null) {
           String nuevaAficion = controller.editarAfición(aficion);
           if (!nuevaAficion.equals(aficion)) {
               listModel.removeElement(aficion);
               listModel.addElement(nuevaAficion);
           }
       }
    }
    
    private void eliminarSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {
       String aficion = jListAficiones.getSelectedValue();
       controller.eliminarAficion(aficion);
       listModel.removeElement(aficion);
    }
      
    private void cambiarSexoActionPerformed(java.awt.event.ActionEvent evt) {
        Genero sexo = controller.cambiarSexo();
        labelSexo.setText(sexo.toString());
    } 
     
    private void cambiarPreferenciaActionPerformed(java.awt.event.ActionEvent evt) {
        Genero preferencia = controller.cambiarPreferencia();
        labelGeneroInteres.setText(preferencia.toString());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirAficion;
    private javax.swing.JTextArea areaDescripcion;
    private javax.swing.JLabel busca;
    private javax.swing.JButton cambiarAvatar;
    private javax.swing.JButton cambiarPreferencia;
    private javax.swing.JButton cambiarSexo;
    private javax.swing.JButton editarSeleccionada;
    private javax.swing.JButton eliminarSeleccionada;
    private javax.swing.JList<String> jListAficiones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAficiones;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelGeneroInteres;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel sexo;
    private abd.p1.view.UserPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
