/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.controller.VentanaPrincipalController;
import abd.p1.model.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

public class panelFiltrarUsuarios extends javax.swing.JPanel {

    private VentanaPrincipalController controller;
    DefaultListModel<Usuario> modelo;
    private String filtro;
    private boolean soloAmigos;

    /**
     * Creates new form panelFiltrarUsuarios
     */
    public panelFiltrarUsuarios() {
        initComponents();
        modelo = new DefaultListModel<>();
        jListUsuarios.setModel(modelo);
        jListUsuarios.setCellRenderer(new UsuarioCellRenderer());
    }
    
    public void setController(VentanaPrincipalController controller) {
        this.controller = controller;
    }
    
    public void cargarListaUsuarios() {
        List<Usuario> usuarios = new ArrayList<Usuario>();
        usuarios = this.controller.cargarListaUsuarios();
        for(Usuario u: usuarios) {
           modelo.addElement(u);
        }
    }
    
    public Usuario getUsuarioSeleccionado() {
        return this.jListUsuarios.getSelectedValue();
    }
    
    public String getFiltro() {
        return filtro;
    }

    public void setFiltro(String filtro) {
        this.filtro = filtro;
    }

    public boolean isSoloAmigos() {
        return soloAmigos;
    }

    public void setSoloAmigos(boolean soloAmigos) {
        this.soloAmigos = soloAmigos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtrarPorNombre = new javax.swing.JCheckBox();
        mostrarSoloAmigos = new javax.swing.JCheckBox();
        textFiltroNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUsuarios = new javax.swing.JList<>();

        filtrarPorNombre.setText("Filtrar por nombre");
        filtrarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarPorNombreActionPerformed(evt);
            }
        });

        mostrarSoloAmigos.setText("Mostrar sólo amigos");

        textFiltroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFiltroNombreActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filtrarPorNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFiltroNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mostrarSoloAmigos)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtrarPorNombre)
                    .addComponent(textFiltroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mostrarSoloAmigos)
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filtrarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarPorNombreActionPerformed
        
    }//GEN-LAST:event_filtrarPorNombreActionPerformed

    private void textFiltroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFiltroNombreActionPerformed
//        if(this.filtrarPorNombre.isSelected()){
//            String filtro = textFiltroNombre.getText();
//            this.modelo.removeAllElements();
//            List<Usuario> listaUsuarios = this.controller.cargarListaUsuariosFiltrados(filtro);
//            if(!listaUsuarios.isEmpty()){
//                for(Usuario usuario: listaUsuarios){
//                    this.modelo.addElement(usuario);
//                }
//            }
//        }
        String filtro = textFiltroNombre.getText();
        this.modelo.removeAllElements();
        List<Usuario> listaUsuarios = this.controller.cargarListaUsuariosFiltradosDistancia(filtro, this.filtrarPorNombre.isSelected());
        if(!listaUsuarios.isEmpty()){
            for(Usuario usuario: listaUsuarios){
                this.modelo.addElement(usuario);
            }
        }
        
    }//GEN-LAST:event_textFiltroNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox filtrarPorNombre;
    private javax.swing.JList<Usuario> jListUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mostrarSoloAmigos;
    private javax.swing.JTextField textFiltroNombre;
    // End of variables declaration//GEN-END:variables
}
