/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.controller.VentanaPrincipalController;
import abd.p1.model.Opcion;
import abd.p1.model.Pregunta;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author enriq
 */
public class panelListaPreguntas extends javax.swing.JPanel {

    private VentanaPrincipalController controller;
    DefaultListModel<Pregunta> modelo;
    /**
     * Creates new form panelListaPreguntas
     */
    public panelListaPreguntas() {
        initComponents();
        this.modelo = new DefaultListModel<>();
        listaPreguntas.setModel(modelo);
        listaPreguntas.setCellRenderer(new PreguntaCellRenderer());
    }
     
    public void setController(VentanaPrincipalController controller) {
        this.controller = controller;
    }
    
    public Pregunta getPreguntaSeleccionada() {
        return listaPreguntas.getSelectedValue();
    }
    
    public void cargarTopPreguntas() {
        List<Pregunta> preguntas = new ArrayList<Pregunta>();
        preguntas = this.controller.cargarListaPreguntas();
        for(Pregunta p: preguntas) {
           modelo.addElement(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPreguntas = new javax.swing.JList<>();

        jRadioButton1.setText("jRadioButton1");

        jScrollPane1.setViewportView(listaPreguntas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Pregunta> listaPreguntas;
    // End of variables declaration//GEN-END:variables

}
