/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.model.Opcion;
import abd.p1.model.Pregunta;
import javax.swing.DefaultListModel;

/**
 *
 * @author enriq
 */
public class ResponderPregunta extends javax.swing.JDialog {

    Pregunta p;
    DefaultListModel listModel;
    /**
     * Creates new form ResponderPregunta
     */
    public ResponderPregunta(){
        super();
        initComponents();
    }
    
    public ResponderPregunta(java.awt.Frame parent, boolean modal, Pregunta p) {
        super(parent, modal);
        initComponents();
        this.p = p;
        rellenar();
        this.sliderRelevancia.setMaximum(10);
        this.sliderRelevancia.setMinimum(0);
        this.sliderRelevancia.setMajorTickSpacing(10);
        this.sliderRelevancia.setMinorTickSpacing(1);
        this.sliderRelevancia.setPaintTicks(true);
        this.sliderRelevancia.setPaintLabels(true);
        listModel = new DefaultListModel();
        this.listaOpciones.setModel(listModel);
        
    }
    
    private void rellenar() {
        this.labelEnunciado.setText(p.getEnunciado());
        for(Opcion o: p.getOpciones()){
            this.listModel.addElement(o.toString());
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEnunciado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaOpciones = new javax.swing.JList<>();
        buttonResponder = new javax.swing.JButton();
        buttonInvitarAUnAmigo = new javax.swing.JButton();
        labelRelevancia = new javax.swing.JLabel();
        sliderRelevancia = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelEnunciado.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        labelEnunciado.setText("Enunciado de la pregunta");

        listaOpciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Rojo", "2. Azul", "3. Verde", "4. Amarillo", "5. Rosa", "6. Ocre", "7. Verde metrosur" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaOpciones);

        buttonResponder.setText("Responder");
        buttonResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResponderActionPerformed(evt);
            }
        });

        buttonInvitarAUnAmigo.setText("Invitar a un amigo");
        buttonInvitarAUnAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvitarAUnAmigoActionPerformed(evt);
            }
        });

        labelRelevancia.setText("Relevancia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEnunciado)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(buttonResponder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonInvitarAUnAmigo)
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelRelevancia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sliderRelevancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEnunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRelevancia)
                    .addComponent(sliderRelevancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonResponder)
                    .addComponent(buttonInvitarAUnAmigo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInvitarAUnAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvitarAUnAmigoActionPerformed
        
    }//GEN-LAST:event_buttonInvitarAUnAmigoActionPerformed

    private void buttonResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResponderActionPerformed
        
    }//GEN-LAST:event_buttonResponderActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ResponderPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ResponderPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ResponderPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ResponderPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ResponderPregunta dialog = new ResponderPregunta(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInvitarAUnAmigo;
    private javax.swing.JButton buttonResponder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEnunciado;
    private javax.swing.JLabel labelRelevancia;
    private javax.swing.JList<String> listaOpciones;
    private javax.swing.JSlider sliderRelevancia;
    // End of variables declaration//GEN-END:variables

    
}
