/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.controller.VentanaPrincipalController;
import abd.p1.model.Pregunta;

/**
 *
 * @author enriq
 */
public class TabPreguntas extends javax.swing.JPanel {

    private VentanaPrincipalController controller;

    /**
     * Creates new form tabPreguntas
     */
    public TabPreguntas() {
        initComponents();
    }
    
    void setController(VentanaPrincipalController controller) {
        this.controller = controller;
        this.panelListaPreguntas1.setController(controller);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListaPreguntas1 = new abd.p1.view.panelListaPreguntas();
        labelMejorValoradas = new javax.swing.JLabel();
        buttonResponder = new javax.swing.JButton();
        buttonPreguntaAleatoria = new javax.swing.JButton();

        labelMejorValoradas.setText("Mejor valoradas:");

        buttonResponder.setText("Responder");
        buttonResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResponderActionPerformed(evt);
            }
        });

        buttonPreguntaAleatoria.setText("Pregunta aleatoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMejorValoradas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonResponder, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(buttonPreguntaAleatoria)))
                .addContainerGap())
            .addComponent(panelListaPreguntas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMejorValoradas)
                .addGap(15, 15, 15)
                .addComponent(panelListaPreguntas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonResponder)
                    .addComponent(buttonPreguntaAleatoria))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResponderActionPerformed
        Pregunta p = this.panelListaPreguntas1.getPreguntaSeleccionada();
        if(p != null)
            this.controller.responderPregunta(p);
    }//GEN-LAST:event_buttonResponderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPreguntaAleatoria;
    private javax.swing.JButton buttonResponder;
    private javax.swing.JLabel labelMejorValoradas;
    private abd.p1.view.panelListaPreguntas panelListaPreguntas1;
    // End of variables declaration//GEN-END:variables

    void cargarTopPreguntas() {
        this.panelListaPreguntas1.cargarTopPreguntas();
    }

    
}
