/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.controller.VentanaPrincipalController;
import abd.p1.model.Usuario;

public class TabUsuarios extends javax.swing.JPanel {

    private VentanaPrincipalController controller;

    /**
     * Creates new form panelUsuarios
     */
    public TabUsuarios() {
        initComponents();
    }
    
    public void setController(VentanaPrincipalController vpc) {
        this.controller = vpc;
        this.panelFiltrarUsuarios1.setController(vpc);
    }
    
    public void cargarListaUsuarios() {
        this.panelFiltrarUsuarios1.cargarListaUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVerPerfilSeleccionado = new javax.swing.JButton();
        buttonModificarPerfil = new javax.swing.JButton();
        panelFiltrarUsuarios1 = new abd.p1.view.panelFiltrarUsuarios();

        buttonVerPerfilSeleccionado.setText("Ver perfil seleccionado");
        buttonVerPerfilSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerPerfilSeleccionadoActionPerformed(evt);
            }
        });

        buttonModificarPerfil.setText("Modificar mi perfil");
        buttonModificarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFiltrarUsuarios1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonModificarPerfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonVerPerfilSeleccionado)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFiltrarUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonModificarPerfil)
                    .addComponent(buttonVerPerfilSeleccionado))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonModificarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarPerfilActionPerformed
        controller.modificarPerfil();
    }//GEN-LAST:event_buttonModificarPerfilActionPerformed

    private void buttonVerPerfilSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerPerfilSeleccionadoActionPerformed
        Usuario seleccionado = panelFiltrarUsuarios1.getUsuarioSeleccionado();
        if (seleccionado != null) {
            controller.verPerfil(seleccionado);
        }
    }//GEN-LAST:event_buttonVerPerfilSeleccionadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonModificarPerfil;
    private javax.swing.JButton buttonVerPerfilSeleccionado;
    private abd.p1.view.panelFiltrarUsuarios panelFiltrarUsuarios1;
    // End of variables declaration//GEN-END:variables
}
