/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;
import abd.p1.controller.ModificarPerfilController;
import abd.p1.model.Usuario;
import java.util.Arrays;
import java.util.Date;
import javax.swing .*;

public class UserPanel extends javax.swing.JPanel {

    private boolean editable;
    private ModificarPerfilController controller;

     /**
     * Creates new form userPanel
     */
    public UserPanel() {
        initComponents();
        inicializarListeners();
    }
    
    public void setController(ModificarPerfilController controller) {
        this.controller = controller;
    }
    
    public ModificarPerfilController getController() {
        return this.controller;
    }
    
    public boolean getEditable(){
        return this.editable;
    }
    
    public void setEditable(boolean e){
        this.editable = e;
        buttonNombre.setVisible(e);
        cambiarFecha.setVisible(e);
    }
    
    public void setIcon(ImageIcon avatar) {
        panelAvatar1.setIcon(avatar);
    }
    
    public void rellenarInfo(String nombre, byte[] imagen, Date fechaNac) {
        labelNombre.setText(nombre);
        //Como la fecha no es un dato necesario puede ser que sea null
        if (fechaNac != null) {
            int edad = Usuario.calcularEdad(fechaNac);
            labelEdad.setText(edad + " años");
        } else {
            labelEdad.setText("Sin especificar");
        }
        //Como la imagen no es un dato necesario puede ser que sea null
        if (imagen != null && imagen.length > 0) {
            setIcon(new ImageIcon(imagen));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonNombre = new javax.swing.JButton();
        labelNombre = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        panelAvatar1 = new abd.p1.view.PanelAvatar();
        cambiarFecha = new javax.swing.JButton();

        buttonNombre.setText("Cambiar nombre");

        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelNombre.setText("Nombre");

        labelEdad.setText("Edad");

        javax.swing.GroupLayout panelAvatar1Layout = new javax.swing.GroupLayout(panelAvatar1);
        panelAvatar1.setLayout(panelAvatar1Layout);
        panelAvatar1Layout.setHorizontalGroup(
            panelAvatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        panelAvatar1Layout.setVerticalGroup(
            panelAvatar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        cambiarFecha.setText("Cambiar fecha de nacimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cambiarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonNombre)
                            .addComponent(labelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEdad)
                            .addComponent(cambiarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

     private void inicializarListeners() {
        buttonNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNombreActionPerformed(evt);
            }
        });

        cambiarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarFechaActionPerformed(evt);
            }
        });
     }
     
    private void buttonNombreActionPerformed(java.awt.event.ActionEvent evt) {
        String nuevoNombre = controller.cambiarNombre();
        if (nuevoNombre != null) {
            labelNombre.setText(nuevoNombre);
        }
    }
    
    private void cambiarFechaActionPerformed(java.awt.event.ActionEvent evt) {
        String edad = controller.cambiarFechaNacimiento();
        if (edad != null) {
            labelEdad.setText(edad);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNombre;
    private javax.swing.JButton cambiarFecha;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelNombre;
    private abd.p1.view.PanelAvatar panelAvatar1;
    // End of variables declaration//GEN-END:variables
}
